pipeline {
  agent any
  stages {
    stage('Prepare') {
      steps {
        sh 'npm install .'
        sh 'ls -la'
        sh 'lein deps'
      }
    }
    stage('unit test') {
      steps {
        sh 'npx --call=\'lein test :default\''
      }
      post {
        always {
          junit 'target/test-reports/*.xml'
          sh 'rm -rf target/test-reports'
        }
      }
    }
   stage('integration test') {
      steps {
        sh 'npx --call=\'shadow-cljs compile app\''
        sh 'npx --call=\'lein test :integration\''
      }
      post {
        always {
          junit 'target/test-reports/*.xml'
          sh 'rm -rf target/test-reports'
        }
      }
    }
    stage('build') {
      steps {
        sh 'npx --call=\'lein uberjar\''
        archiveArtifacts artifacts: 'target/uberjar/lum.jar'
      }
    }
  }
}
