pipeline {
  agent any
  parameters {
    booleanParam(name: 'BUILD', defaultValue: false, description: 'Build jar file')
  }
  stages {
    stage('Prepare') {
      steps {
        sh 'npm install .'
      }
    }
   stage('test') {
      steps {
        sh 'npx --call=\'lein test :all\''
      }
      post {
        always {
          junit 'target/test-reports/*.xml'
          sh 'rm -rf target/test-reports'
        }
      }
    }
    stage('publish') {
      steps {
        sh '.jenkins/publish.sh'
      }
    }
    stage('build') {
      when {
        expression{ return params.BUILD }
      }
      steps {
        sh 'npx --call=\'lein uberjar\''
        archiveArtifacts artifacts: 'target/uberjar/lum.jar'
      }
    }
  }
}
