name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies npm
      run: npm install .
    - name: Install dependencies lein
      run: npx lein deps
    - name: Compile cljs code
      run: npx shadow-cljs compile app
    - name: Run tests
      run: npx lein test :all
